# Generated by Django 5.2.4 on 2025-07-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='foi_pago',
            field=models.BooleanField(default=False),
        ),
    ]
