# Generated by Django 5.2.4 on 2025-07-10 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_lancamento_foi_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='vencimento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
